blank_issues_enabled: false
contact_links:
  - name: Contact Us 
    url: https://www.africtivistes.com/en/nous-contacter/
    about: Contact us for all other question ?
  - name: About - AfricTivistes 
    url: https://www.africtivistes.com/en/africtivistes/
    about: About, The African League of Bloggers and Cyber-activists for Democracy